apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-eu-

resources:
- ../../base

components:
  - ../../variants/prod
  - ../../variants/eu

patches:
- path: deployment.yml
- path: version.yml
- path: replicas.yml
- path: settings.yml

