on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:


permissions:
  contents: read

name: Diff GitOps Environments

jobs:
  diff-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
         path: pr
      - name: Checkout Target of PR
        uses: actions/checkout@v3
        with:
          path: target
          ref: ${{ github.event.pull_request.base.ref }}

      - run: ls -la
      - run: ls -la pr
      - run: ls -la target
      - run: diff -v
      - run: cat pr/envs/qa/settings.yml
      - run: cat target/envs/qa/settings.yml
      - run: ls -ld . 
      - run: touch now.md
      - run: mkdir lala
      - run: ls -la
      - run: diff pr/envs/qa/settings.yml target/envs/qa/settings.yml || true
      - run: diff pr/envs/qa/settings.yml target/envs/qa/settings.yml > /tmp/changes.diff || true
      - run: cat changes.diff
