on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:


permissions:
  contents: read

name: Diff GitOps Environments

jobs:
  diff-env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         path: pr

      - run: ls -la
